services:
  user_service:
    image: user_service:1.0
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  
  consumer_a:
    image: consumer_a:1.0
    build:
      context: ./consumer_a
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - USER_API_HOST=http://user_service:8081

  web_ui:
    image: web_ui:1.0
    build:
      context: ./web/user-web
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    environment:
      - API_BASE_URL=http://localhost:8081